// Code generated by MockGen. DO NOT EDIT.
// Source: routes.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockRouterService is a mock of RouterService interface.
type MockRouterService struct {
	ctrl     *gomock.Controller
	recorder *MockRouterServiceMockRecorder
}

// MockRouterServiceMockRecorder is the mock recorder for MockRouterService.
type MockRouterServiceMockRecorder struct {
	mock *MockRouterService
}

// NewMockRouterService creates a new mock instance.
func NewMockRouterService(ctrl *gomock.Controller) *MockRouterService {
	mock := &MockRouterService{ctrl: ctrl}
	mock.recorder = &MockRouterServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRouterService) EXPECT() *MockRouterServiceMockRecorder {
	return m.recorder
}

// LoadRoutes mocks base method.
func (m *MockRouterService) LoadRoutes() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "LoadRoutes")
}

// LoadRoutes indicates an expected call of LoadRoutes.
func (mr *MockRouterServiceMockRecorder) LoadRoutes() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoadRoutes", reflect.TypeOf((*MockRouterService)(nil).LoadRoutes))
}
